# Generated by Django 2.2.16 on 2021-05-31 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=30)),
                ('probleme_ram', models.TextField(blank=True, max_length=200)),
                ('probleme_os', models.TextField(blank=True, max_length=200)),
                ('probleme_dd', models.TextField(blank=True, max_length=200)),
                ('probleme_alimentation_affichage', models.TextField(blank=True, max_length=200)),
                ('autre_probleme', models.TextField(blank=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('parc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
